Add home page
dinchen1089/CultFitClone pull request #7
Opened 2023-11-14 10:17 UTC by usq2

- Added all non animated home page components

2023-11-19 15:42 UTC, dinchen1089 requested changes

2023-11-19 15:42 UTC, dinchen1089 commented on src/component/ui_helpers/ProfileButton.jsx
> +        <Text style={styles.profileButtonText}>D</Text>
D can be passed as a parameter

2023-11-19 15:42 UTC, dinchen1089 commented on src/component_data/secondaryActionsData.js
> +      console.log('weight lifter pressed');
Remove this

2023-11-19 15:42 UTC, dinchen1089 commented on src/component_data/secondaryActionsData.js
> +      console.log('buy sports wear pressed');
Remove this or add todo if required

2023-11-19 15:42 UTC, dinchen1089 commented on src/images/imageMap.js
> +      'Make stubborn fat disappear with sustainable weight loss coaching',
Add this text in english if this text wont change

2023-11-19 15:42 UTC, dinchen1089 commented on src/screen/Home.js
> +          Everything you need to stay inspired & stay on top of your game
Add his text in english file

2023-12-13 08:52 UTC, usq2 commented on src/component_data/secondaryActionsData.js
> +      console.log('weight lifter pressed');
no i will not

2023-12-13 09:25 UTC, merged